name: Continuous Deployment

on:
  push:
    branches: [dev]
    paths:
      - ".github/workflows/deploy.yaml"
  repository_dispatch:
    types:
      - backend-image-pushed
      - frontend-image-pushed
      - terraform-completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Terraform outputs
        uses: actions/download-artifact@v4
        with:
          name: terraform-outputs
          path: ./terraform-data
        continue-on-error: true

      - name: Load Terraform outputs
        run: |
          if [ -f ./terraform-data/outputs.env ]; then
            cat ./terraform-data/outputs.env >> $GITHUB_ENV
            echo "Terraform outputs loaded."
          else
            echo "Terraform outputs missing. Deploy skipped."
            exit 0
          fi

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Copy files & deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ env.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cat <<EOF > /home/${{ secrets.EC2_USER }}/dream-app/.env
            DB_USER=${{ secrets.DATABASE_USER }}
            DB_PASS=${{ secrets.DATABASE_PASSWD }}
            EOF

            cd /home/${{ secrets.EC2_USER }}/dream-app
            docker compose pull
            docker compose up -d --build

      - name: Health check
        run: |
          sleep 30
          timeout 120 bash -c 'until curl -f http://${{ env.EC2_PUBLIC_IP }}:80; do sleep 5; done' || echo "Frontend may not be ready"
          timeout 120 bash -c 'until curl -f http://${{ env.EC2_PUBLIC_IP }}:3001; do sleep 5; done' || echo "Backend may not be ready"
