name: Backend Continuous Integration Workflow

on:
  push:
    branches: [dev]
    paths:
      - "frontend/**"
  pull_request:
    branches: [dev]
    paths:
      - "frontend/**"
      - ".github/workflows/**"

env:
  IMAGE_NAME: temmytope/dream-vac-fe

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Show commit SHA
        run: echo ${{ github.sha }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend  # Adjust to your actual Docker context
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}
